from utils.mt5_client import mt5

ORDER_STATE_MAP = {
    "STARTED": mt5.ORDER_STATE_STARTED,
    "PLACED": mt5.ORDER_STATE_PLACED,
    "CANCELED": mt5.ORDER_STATE_CANCELED,
    "PARTIAL": mt5.ORDER_STATE_PARTIAL,
    "FILLED": mt5.ORDER_STATE_FILLED,
    "REJECTED": mt5.ORDER_STATE_REJECTED,
    "EXPIRED": mt5.ORDER_STATE_EXPIRED,
    "REQUEST_ADD": mt5.ORDER_STATE_REQUEST_ADD,
    "REQUEST_MODIFY": mt5.ORDER_STATE_REQUEST_MODIFY,
    "REQUEST_CANCEL": mt5.ORDER_STATE_REQUEST_CANCEL
}